# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1100, 650)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setDocumentMode(False)
        self.mainWidget = QtWidgets.QWidget(mainWindow)
        self.mainWidget.setObjectName("mainWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mapWidget = QtWidgets.QWidget(self.mainWidget)
        self.mapWidget.setStyleSheet("#mapWidget{\n"
"background-color:rgb(231, 231, 231)\n"
"}")
        self.mapWidget.setObjectName("mapWidget")
        self.horizontalLayout.addWidget(self.mapWidget)
        mainWindow.setCentralWidget(self.mainWidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 23))
        self.menubar.setObjectName("menubar")
        self.mnFile = QtWidgets.QMenu(self.menubar)
        self.mnFile.setObjectName("mnFile")
        self.muTools = QtWidgets.QMenu(self.menubar)
        self.muTools.setObjectName("muTools")
        self.mnViews = QtWidgets.QMenu(self.menubar)
        self.mnViews.setObjectName("mnViews")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.openToolBar = QtWidgets.QToolBar(mainWindow)
        self.openToolBar.setObjectName("openToolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.openToolBar)
        self.tbShowByAttrs = QtWidgets.QToolBar(mainWindow)
        self.tbShowByAttrs.setObjectName("tbShowByAttrs")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.tbShowByAttrs)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget = QtWidgets.QDockWidget(mainWindow)
        self.dockWidget.setMinimumSize(QtCore.QSize(150, 38))
        self.dockWidget.setStyleSheet("#dockWidget_2{\n"
"background-color:rgb(226, 255, 249)\n"
"}")
        self.dockWidget.setObjectName("dockWidget")
        self.treeViews = QtWidgets.QWidget()
        self.treeViews.setStyleSheet("#treeViews{\n"
"background-color:rgb(217, 255, 230)\n"
"}")
        self.treeViews.setObjectName("treeViews")
        self.dockWidget.setWidget(self.treeViews)
        mainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.openShpAction = QtWidgets.QAction(mainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icos/openV.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openShpAction.setIcon(icon1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.openShpAction.setFont(font)
        self.openShpAction.setObjectName("openShpAction")
        self.openRasterAction = QtWidgets.QAction(mainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icos/openR.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openRasterAction.setIcon(icon2)
        self.openRasterAction.setObjectName("openRasterAction")
        self.openGeojsonAction = QtWidgets.QAction(mainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icos/openG.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openGeojsonAction.setIcon(icon3)
        self.openGeojsonAction.setObjectName("openGeojsonAction")
        self.mbShowByAttrs = QtWidgets.QAction(mainWindow)
        self.mbShowByAttrs.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icos/showbyattrs.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mbShowByAttrs.setIcon(icon4)
        self.mbShowByAttrs.setObjectName("mbShowByAttrs")
        self.actioncc = QtWidgets.QAction(mainWindow)
        self.actioncc.setObjectName("actioncc")
        self.showTuCengAction = QtWidgets.QAction(mainWindow)
        self.showTuCengAction.setCheckable(True)
        self.showTuCengAction.setChecked(True)
        self.showTuCengAction.setEnabled(True)
        self.showTuCengAction.setObjectName("showTuCengAction")
        self.mnFile.addAction(self.openShpAction)
        self.mnFile.addAction(self.openRasterAction)
        self.mnFile.addAction(self.openGeojsonAction)
        self.muTools.addAction(self.mbShowByAttrs)
        self.muTools.addAction(self.actioncc)
        self.mnViews.addAction(self.showTuCengAction)
        self.menubar.addAction(self.mnFile.menuAction())
        self.menubar.addAction(self.muTools.menuAction())
        self.menubar.addAction(self.mnViews.menuAction())
        self.openToolBar.addAction(self.openShpAction)
        self.openToolBar.addAction(self.openRasterAction)
        self.openToolBar.addAction(self.openGeojsonAction)
        self.tbShowByAttrs.addAction(self.mbShowByAttrs)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "ynlh-GIS"))
        mainWindow.setToolTip(_translate("mainWindow", "欢迎来到德莱联盟"))
        self.mnFile.setTitle(_translate("mainWindow", "文件"))
        self.muTools.setTitle(_translate("mainWindow", "工具"))
        self.mnViews.setTitle(_translate("mainWindow", "视图"))
        self.openToolBar.setWindowTitle(_translate("mainWindow", "打开文件"))
        self.openToolBar.setToolTip(_translate("mainWindow", "打开文件工具条"))
        self.openToolBar.setWhatsThis(_translate("mainWindow", "<html><head/><body><p><span style=\" font-style:italic;\">打开文件工具条</span></p></body></html>"))
        self.tbShowByAttrs.setWindowTitle(_translate("mainWindow", "newmap"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "工具"))
        self.toolBar.setToolTip(_translate("mainWindow", "工具"))
        self.dockWidget.setWindowTitle(_translate("mainWindow", "图层管理"))
        self.openShpAction.setText(_translate("mainWindow", "加载shp文件"))
        self.openShpAction.setShortcut(_translate("mainWindow", "Ctrl+O, Ctrl+V"))
        self.openRasterAction.setText(_translate("mainWindow", "加载影像数据"))
        self.openRasterAction.setShortcut(_translate("mainWindow", "Ctrl+O, Ctrl+R"))
        self.openGeojsonAction.setText(_translate("mainWindow", "加载Geojson文件"))
        self.openGeojsonAction.setShortcut(_translate("mainWindow", "Ctrl+O, Ctrl+G"))
        self.mbShowByAttrs.setText(_translate("mainWindow", "按属性显示地块"))
        self.actioncc.setText(_translate("mainWindow", "cc"))
        self.showTuCengAction.setText(_translate("mainWindow", "图层管理"))

from . import lhqgis_rc
