# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showByAttrs.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_showByAttrsForm(object):
    def setupUi(self, showByAttrsForm):
        showByAttrsForm.setObjectName("showByAttrsForm")
        showByAttrsForm.resize(1135, 688)
        showByAttrsForm.setMinimumSize(QtCore.QSize(700, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        showByAttrsForm.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(showByAttrsForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wgLoadControl = QtWidgets.QWidget(showByAttrsForm)
        self.wgLoadControl.setEnabled(True)
        self.wgLoadControl.setMinimumSize(QtCore.QSize(200, 38))
        self.wgLoadControl.setMaximumSize(QtCore.QSize(200, 16777215))
        self.wgLoadControl.setStyleSheet("#wgLoadControl{\n"
"background-color:rgb(212, 255, 246);\n"
"border-width:4px;\n"
"}")
        self.wgLoadControl.setObjectName("wgLoadControl")
        self.sldShowByAttrs = QtWidgets.QSlider(self.wgLoadControl)
        self.sldShowByAttrs.setGeometry(QtCore.QRect(0, 200, 191, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sldShowByAttrs.sizePolicy().hasHeightForWidth())
        self.sldShowByAttrs.setSizePolicy(sizePolicy)
        self.sldShowByAttrs.setMinimumSize(QtCore.QSize(140, 0))
        self.sldShowByAttrs.setMaximum(1)
        self.sldShowByAttrs.setPageStep(1)
        self.sldShowByAttrs.setProperty("value", 0)
        self.sldShowByAttrs.setOrientation(QtCore.Qt.Horizontal)
        self.sldShowByAttrs.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sldShowByAttrs.setTickInterval(1)
        self.sldShowByAttrs.setObjectName("sldShowByAttrs")
        self.cbShowAll = QtWidgets.QCheckBox(self.wgLoadControl)
        self.cbShowAll.setGeometry(QtCore.QRect(0, 140, 131, 16))
        self.cbShowAll.setObjectName("cbShowAll")
        self.layoutWidget = QtWidgets.QWidget(self.wgLoadControl)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 60, 202, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cbFields = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbFields.sizePolicy().hasHeightForWidth())
        self.cbFields.setSizePolicy(sizePolicy)
        self.cbFields.setMinimumSize(QtCore.QSize(190, 0))
        self.cbFields.setMaximumSize(QtCore.QSize(190, 16777215))
        self.cbFields.setCurrentText("")
        self.cbFields.setObjectName("cbFields")
        self.verticalLayout.addWidget(self.cbFields)
        self.layoutWidget1 = QtWidgets.QWidget(self.wgLoadControl)
        self.layoutWidget1.setGeometry(QtCore.QRect(6, 0, 144, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pbLoadFile = QtWidgets.QPushButton(self.layoutWidget1)
        self.pbLoadFile.setMinimumSize(QtCore.QSize(75, 0))
        self.pbLoadFile.setObjectName("pbLoadFile")
        self.horizontalLayout_2.addWidget(self.pbLoadFile)
        spacerItem1 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.sldCurrentValue = QtWidgets.QLabel(self.wgLoadControl)
        self.sldCurrentValue.setGeometry(QtCore.QRect(0, 250, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sldCurrentValue.setFont(font)
        self.sldCurrentValue.setText("")
        self.sldCurrentValue.setObjectName("sldCurrentValue")
        self.horizontalLayout.addWidget(self.wgLoadControl)
        self.wgMap = QtWidgets.QWidget(showByAttrsForm)
        self.wgMap.setMinimumSize(QtCore.QSize(500, 350))
        self.wgMap.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.wgMap.setStyleSheet("#wgMap{\n"
"background:rgb(243, 255, 226)\n"
"}")
        self.wgMap.setObjectName("wgMap")
        self.horizontalLayout.addWidget(self.wgMap)

        self.retranslateUi(showByAttrsForm)
        QtCore.QMetaObject.connectSlotsByName(showByAttrsForm)

    def retranslateUi(self, showByAttrsForm):
        _translate = QtCore.QCoreApplication.translate
        showByAttrsForm.setWindowTitle(_translate("showByAttrsForm", "按属性显示地块"))
        self.cbShowAll.setText(_translate("showByAttrsForm", "显示满足条件的所有"))
        self.label.setText(_translate("showByAttrsForm", "选择属性："))
        self.pbLoadFile.setText(_translate("showByAttrsForm", "加载shp文件"))
from . import lhqgis_rc
